version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_tienda_motos
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tienda_motos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tienda_motos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    shm_size: 256mb
  backend:
    build: ./backend
    container_name: backend_motos
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tienda_motos
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend:
    build: ./frontend
    container_name: frontend_motos
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://138.197.218.131:8000
    ports:
      - "3000:3000"

volumes:
  db_data:

