version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_tienda_motos
    environment:
      - POSTGRES_DB=tienda_motos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend_motos
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tienda_motos
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: frontend_motos
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://138.197.218.131:8000
    ports:
      - "3000:3000"

volumes:
  db_data:

